### ISSUE TITLE
Removing the database connectivity out of the main code

### ISSUE THREAD

**Issue by geekypandey** [sinha-debojyoti/Ookla-Speedtest.net-Crawler#10]
Cleaning the main code and moving MySQL connectivity to outside so the code becomes easier to navigate.

**Comment by chavarera** [comment]
i would like to work on it

**Comment by sinha-debojyoti** [comment]
@chavarera carry on.

**Comment by geekypandey** [comment]
I started working on it already. Almost done. Sorry,I should have mentioned earlier.

**Comment by chavarera** [comment]
Carry on @geekypandey

**Comment by chavarera** [comment]
@geekypandey I have already completed  90% 😢

**Comment by geekypandey** [comment]
@chavarera  Could we just compare and merge our work together , so neither of our work goes waste.
Extremely sorry for the confusion.

> @geekypandey I have already completed 90%

**Comment by sinha-debojyoti** [comment]
@chavarera you can optimize the code of @geekypandey 
 I am not closing the issue.

**Comment by chavarera** [comment]
Mark it as closed
