### ISSUE TITLE
@chavarera @geekypandey add documentation for  database.

### ISSUE THREAD

**Issue by sinha-debojyoti** [sinha-debojyoti/Ookla-Speedtest.net-Crawler#18]
@chavarera @geekypandey add documentation for  #database.

_Originally posted by @sinha-debojyoti in https://github.com/sinha-debojyoti/Ookla-Speedtest.net-Crawler/issues/5#issuecomment-566186555_

**Comment by geekypandey** [comment]
Okay.Working on it now.
