### ISSUE TITLE
Can anyone add Parallel Processing?

### ISSUE THREAD

**Issue by sinha-debojyoti** [sinha-debojyoti/Ookla-Speedtest.net-Crawler#2]
Parallel processing is a mode of operation where the task is executed simultaneously in multiple processors on the same computer. It is meant to reduce the overall processing time. A pooling of the URLs can be done.

**Comment by sinha-debojyoti** [comment]
Rajat had completed the task.

**Comment by sinha-debojyoti** [comment]
@geekypandey have some issue.

**Comment by chavarera** [comment]
What issues

**Comment by geekypandey** [comment]
I was not able to get it running with my code . I made logical error. The fetched data was not storing in the database. Now it is running. It takes about 40 seconds for 100 pages . I am running it on 4 core PC . With that it would take around 117 years. What do you suggest to improve the speed on execution? Also for the code the race conditions is not checked. Will have to look into it.
