### ISSUE TITLE
@chavarera #14  doesn't fix the upload and download speed problem.

### ISSUE THREAD

**Issue by sinha-debojyoti** [sinha-debojyoti/Ookla-Speedtest.net-Crawler#20]
@chavarera #14  doesn't fix the problem. 
For speedtest.com/result/1000000000 the upload and download speed are coming to be 0.

_Originally posted by @geekypandey in https://github.com/sinha-debojyoti/Ookla-Speedtest.net-Crawler/issues/12#issuecomment-566370508_

**Comment by chavarera** [comment]
@sinha-debojyoti let me check it.

**Comment by chavarera** [comment]
@sinha-debojyoti Its Working Perfectly. I have Tested Thrice

**Comment by sinha-debojyoti** [comment]
@geekypandey, please review it.

**Comment by geekypandey** [comment]
**This is the result after crawling 10 pages. Check for the path = /result/1000000000 and others too.** 

![checkcheck](https://user-images.githubusercontent.com/24317727/71012968-f06e1f00-2115-11ea-835d-9dffdb3cab7a.png)
![Screenshot from 2019-12-17 21-40-34](https://user-images.githubusercontent.com/24317727/71012969-f06e1f00-2115-11ea-9350-7e631104b959.png)

@chavarera Could you please upload your output ?

**Comment by chavarera** [comment]
@geekypandey  and @sinha-debojyoti this issue is solved by changing type of elements into table
Previous int datatype
0.35--->to int 0

Now decimal
0.35--> to decimal save 0.35 same value

**Comment by geekypandey** [comment]
yes, it works now.

**Comment by chavarera** [comment]
@geekypandey thanks for acknowledging
Because Currently I am away from my laptop

The issue is only datatype mismatching in tables
