### ISSUE TITLE
Implementation of ray module instead of multiprocessing module which increase the speed of crawling.

### ISSUE THREAD

**Issue by sinha-debojyoti** [sinha-debojyoti/Ookla-Speedtest.net-Crawler#23]

**Comment by geekypandey** [comment]
Could you please assign this to me?

**Comment by PiranavS** [comment]
How do I start working on this issue?

**Comment by sinha-debojyoti** [comment]
main.py multiprocessing library is implemented. @PiranavS you need to replace the multiprocessing library with the ray library.

**Comment by PiranavS** [comment]
How do I submit my work?

**Comment by sinha-debojyoti** [comment]
@PiranavS need to fork the project. Then apply the changes. Then you need to create a pull request. If your work satisfied me I will merge the pull request. 
@PiranavS can also use the GitHub desktop, to make this submission process smooth.

**Comment by sinha-debojyoti** [comment]
@PiranavS completed this work.
